name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths: [ "Makefile", "src/**", "test/**" ]

  pull_request:
    branches: [ "main" ]
    paths: [ "Makefile", "src/**", "test/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest
      run: sudo apt-get install libgtest-dev
    - uses: actions/checkout@v4
    - name: build project
      run: make
    - name: run tests
      run: make test